apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mysql
  labels:
    app: deployment-mysql
spec:
  template:
    metadata:
      name: pod-mysql
      labels:
        tier: db-mysql
    spec:
      containers:
        - name: mysql
          # resources:
          #   limits:
          #     memory: "512Mi"
          #     cpu: "900m"
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
            - name: MYSQL_ROOT_HOST
              value: "%"
          ports:
            - containerPort: 3306
              name: port-mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: persistent-storage-mysql
      volumes:
        - name: persistent-storage-mysql
          persistentVolumeClaim:
            claimName: mysql-pv-claim

  replicas: 1
  selector:
    matchLabels:
      tier: db-mysql
  strategy:
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-wordpress
  labels:
    app: deployment-wordpress
spec:
  template:
    metadata:
      name: pod-wordpress
      labels:
        tier: frontend-wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:4.8-apache
          # resources:
          #   limits:
          #     memory: "256Mi"
          #     cpu: "500m"
          env:
            - name: WORDPRESS_DB_HOST
              value: svc-mysql
            - name: WORDPRESS_DB_PASSWORD
              value: "rootpassword"
          ports:
            - containerPort: 80
              name: port-wordpress
          volumeMounts:
            - mountPath: /var/www/html
              name: persistent-storage-wordpress
      volumes:
        - name: persistent-storage-wordpress
          persistentVolumeClaim:
            claimName: wordpress-pv-claim

  replicas: 1
  selector:
    matchLabels:
      tier: frontend-wordpress
  strategy:
    type: Recreate
