apiVersion: v1
kind: Service
metadata:
  name: svc-wordpress
  labels:
    tier: frontend-wordpress
spec:
  type: NodePort
  selector:
    tier: pod-wordpress
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mysql
  labels:
    tier: db-mysql
spec:
  ports:
    - port: 3306
  selector:
    tier: db-mysql
